In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf
import glob
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.utils import compute_class_weight

Get the input and label files from CSVs

In [9]:
def get_train_test_splitted_data(label_files, input_files, global_mean, global_std, test_size=0.2, random_state=42):
    # Initialize lists to hold all sequences
    all_x_sequences = []
    all_y_sequences = []

    # Process each pair of input and label files
    for input_file, label_file in zip(input_files, label_files):
        # Load data
        input_df = pd.read_csv(input_file)
        if label_file.endswith('BORIS_method_II.csv'):
            label_df = pd.read_csv(label_file)
        else:
            label_df = pd.read_csv(label_file, dtype=str, na_values=[])    
        # Prepare features and labels
        features = (input_df.values - global_mean) / global_std
        
        if label_file.endswith('BORIS_method_II.csv'):
            labels = label_df.values / 100
        else:
            # Define the possible categories explicitly
            column_names = ['Happy', 'Sad', 'Scared', 'Disgusted', 'Surprised', 'Angry']

            # Create a OneHotEncoder with predefined categories
            encoder = OneHotEncoder(categories=[column_names], handle_unknown='ignore')

            # Fit and transform the label data
            labels = pd.DataFrame(
                encoder.fit_transform(label_df).toarray(),
                columns=encoder.get_feature_names_out()
            )

        # Ensure alignment of frames
        if features.shape[0] != labels.shape[0]:
            print(f"Mismatch in frames: {input_file}, {label_file}")
            continue
            
        # Sample sequences
        x_sequences, y_sequences = create_sequences(features, labels, SEQUENCE_LENGTH, STRIDE)

        # Append to global lists
        all_x_sequences.append(x_sequences)
        all_y_sequences.append(y_sequences)
        
    # Concatenate all sequences from all files
    all_x_sequences = np.concatenate(all_x_sequences, axis=0)
    all_y_sequences = np.concatenate(all_y_sequences, axis=0)

    # Split into train and test sets
    X_train, X_test, y_train, y_test = train_test_split(
        all_x_sequences, all_y_sequences, test_size=test_size, random_state=random_state
    )

    # Convert to TensorFlow datasets
    train_dataset = tf.data.Dataset.from_tensor_slices((X_train, y_train))
    test_dataset = tf.data.Dataset.from_tensor_slices((X_test, y_test))

    # Shuffle, batch, and prefetch
    train_dataset = train_dataset.shuffle(buffer_size=10000).batch(BATCH_SIZE).prefetch(tf.data.experimental.AUTOTUNE)
    test_dataset = test_dataset.batch(BATCH_SIZE).prefetch(tf.data.experimental.AUTOTUNE)

    return train_dataset, test_dataset

In [10]:
# Constants
SEQUENCE_LENGTH = 20
STRIDE = 10
BATCH_SIZE = 32
INPUT_DIM = 515  # Number of features per frame (e.g., biosignals + embeddings)
OUTPUT_DIM = 6 

In [11]:
# Helper function to create random sequences
def create_sequences(features, labels, sequence_length, stride):
    x_sequences, y_sequences = [], []
    for i in range(0, len(features) - sequence_length + 1, stride):
        x_sequences.append(features[i:i + sequence_length])
        y_sequences.append(labels[i:i + sequence_length])
    return np.array(x_sequences), np.array(y_sequences)

# Initialize lists to hold all sequences
all_x_sequences = []
all_y_sequences = []
all_features = []

sources = ["GUT", "ITU-YU", "MAAP"]
base_path = "//153.19.52.107/emboa/IO3-sessions/NEW STRUCTURE/de-earlyfusionthesis/"
input_files, label_files = [], []

for source in sources:
    input_files.extend(glob.glob(os.path.join(base_path, source, '*_input.csv')))
    label_files.extend(glob.glob(os.path.join(base_path, source, '*_BORIS.csv')))

input_files.sort()
label_files.sort()

i = 0
for input_file in input_files:
    input_df = pd.read_csv(input_file)
    all_features.append(input_df.values)

# Concatenate all features from all files to compute global mean and std
all_features = np.concatenate(all_features, axis=0)

num_columns = all_features.shape[1]
global_mean_zero = np.zeros(num_columns)
global_std_zero = np.zeros(num_columns)

# Compute column-wise statistics ignoring zeros
for col in range(num_columns):
    non_zero_col = all_features[:, col][all_features[:, col] != 0]  # Filter non-zero values
    if non_zero_col.size > 0:  # Avoid empty arrays
        global_mean_zero[col] = np.mean(non_zero_col)
        global_std_zero[col] = np.std(non_zero_col, ddof=1)  # Use sample std dev
    else:
        global_mean_zero[col] = 0  # Default if no non-zero elements
        global_std_zero[col] = 0

# Output results as ndarray
global_mean = np.array(global_mean_zero)
global_std = np.array(global_std_zero)


In [12]:

GUT_path_input = sorted(glob.glob('//153.19.52.107/emboa/IO3-sessions/NEW STRUCTURE/de-earlyfusionthesis/GUT/*_input.csv'))
ITU_YU_path_input = sorted(glob.glob('//153.19.52.107/emboa/IO3-sessions/NEW STRUCTURE/de-earlyfusionthesis/ITU-YU/*_input.csv'))
MAAP_path_input = sorted(glob.glob('//153.19.52.107/emboa/IO3-sessions/NEW STRUCTURE/de-earlyfusionthesis/MAAP/*_input.csv'))

GUT_path_label_method_I = sorted(glob.glob('//153.19.52.107/emboa/IO3-sessions/NEW STRUCTURE/de-earlyfusionthesis/GUT/*_BORIS_method_I.csv'))
ITU_YU_path_label_method_I = sorted(glob.glob('//153.19.52.107/emboa/IO3-sessions/NEW STRUCTURE/de-earlyfusionthesis/ITU-YU/*_BORIS_method_I.csv'))
MAAP_path_label_method_I = sorted(glob.glob('//153.19.52.107/emboa/IO3-sessions/NEW STRUCTURE/de-earlyfusionthesis/MAAP/*_BORIS_method_I.csv'))

GUT_path_label_method_II = sorted(glob.glob('//153.19.52.107/emboa/IO3-sessions/NEW STRUCTURE/de-earlyfusionthesis/GUT/*_BORIS_method_II.csv'))
ITU_YU_path_label_method_II = sorted(glob.glob('//153.19.52.107/emboa/IO3-sessions/NEW STRUCTURE/de-earlyfusionthesis/ITU-YU/*_BORIS_method_II.csv'))
MAAP_path_label_method_II = sorted(glob.glob('//153.19.52.107/emboa/IO3-sessions/NEW STRUCTURE/de-earlyfusionthesis/MAAP/*_BORIS_method_II.csv'))

GUT_train_method_I, GUT_test_method_I = get_train_test_splitted_data(GUT_path_label_method_I, GUT_path_input, global_mean, global_std, test_size=0.3)
ITU_YU_train_method_I, ITU_YU_test_method_I = get_train_test_splitted_data(ITU_YU_path_label_method_I, ITU_YU_path_input, global_mean, global_std, test_size=0.3)
MAAP_train_method_I, MAAP_test_method_I = get_train_test_splitted_data(MAAP_path_label_method_I, MAAP_path_input, global_mean, global_std, test_size=0.3)

GUT_train_method_II, GUT_test_method_II = get_train_test_splitted_data(GUT_path_label_method_II, GUT_path_input, global_mean, global_std, test_size=0.3)
ITU_YU_train_method_II, ITU_YU_test_method_II = get_train_test_splitted_data(ITU_YU_path_label_method_II, ITU_YU_path_input, global_mean, global_std, test_size=0.3)
MAAP_train_method_II, MAAP_test_method_II = get_train_test_splitted_data(MAAP_path_label_method_II, MAAP_path_input, global_mean, global_std, test_size=0.3)

dataset_method_I = GUT_train_method_I.concatenate(ITU_YU_train_method_I).concatenate(MAAP_train_method_I)
dataset_method_II = GUT_train_method_II.concatenate(ITU_YU_train_method_II).concatenate(MAAP_train_method_II)

In [16]:
import pandas as pd
import numpy as np

all_features = []

for input_file in input_files:
    input_df = pd.read_csv(input_file)
    
    # Check if the DataFrame contains any NaN
    if input_df.isnull().values.any():
        print(f"NaN found in file: {input_file}")
    
    all_features.append(input_df.values)

In [13]:
path = r'S:\IO3-sessions\NEW STRUCTURE\de-earlyfusionthesis\Datasets'

tf.data.Dataset.save(dataset_method_I ,os.path.join(path, 'train_dataset_method_I'))
tf.data.Dataset.save(GUT_train_method_I, os.path.join(path, 'GUT_train_method_I'))
tf.data.Dataset.save(GUT_test_method_I, os.path.join(path, 'GUT_test_method_I'))
tf.data.Dataset.save(ITU_YU_train_method_I, os.path.join(path, 'ITU_YU_train_method_I'))
tf.data.Dataset.save(ITU_YU_test_method_I, os.path.join(path, 'ITU_YU_test_method_I'))
tf.data.Dataset.save(MAAP_train_method_I, os.path.join(path, 'MAAP_train_method_I'))
tf.data.Dataset.save(MAAP_test_method_I, os.path.join(path, 'MAAP_test_method_I'))

tf.data.Dataset.save(dataset_method_II ,os.path.join(path, 'train_dataset_method_II'))
tf.data.Dataset.save(GUT_train_method_II, os.path.join(path, 'GUT_train_method_II'))
tf.data.Dataset.save(GUT_test_method_II, os.path.join(path, 'GUT_test_method_II'))
tf.data.Dataset.save(ITU_YU_train_method_II, os.path.join(path, 'ITU_YU_train_method_II'))
tf.data.Dataset.save(ITU_YU_test_method_II, os.path.join(path, 'ITU_YU_test_method_II'))
tf.data.Dataset.save(MAAP_train_method_II, os.path.join(path, 'MAAP_train_method_II'))
tf.data.Dataset.save(MAAP_test_method_II, os.path.join(path, 'MAAP_test_method_II'))

In [14]:
path = r'S:\IO3-sessions\NEW STRUCTURE\de-earlyfusionthesis\Models'

## MODEL I

In [55]:
model_I = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(SEQUENCE_LENGTH, INPUT_DIM)),    # Input shape: (sequence_length, features)
    tf.keras.layers.LSTM(64, return_sequences=True),              # LSTM layer to capture temporal patterns
    tf.keras.layers.Dense(32, activation='relu'),                 # Dense layer to reduce dimensionality
    tf.keras.layers.Dense(OUTPUT_DIM, activation='softmax')       # Output layer with sigmoid for continuous values between 0 and 1
])

In [15]:
def custom_masking(inputs):
    # Create a mask where any feature being 0 masks the entire time step
    mask = tf.reduce_all(tf.not_equal(inputs, 0.0), axis=-1)  # True if no feature is 0
    return tf.where(mask[:, :, tf.newaxis], inputs, tf.zeros_like(inputs))

# Model with custom masking
model_I = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(SEQUENCE_LENGTH, INPUT_DIM)),   # Input shape
    tf.keras.layers.Lambda(custom_masking),                      # Custom masking layer
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64, return_sequences=True)),  # Bidirectional LSTM
    tf.keras.layers.Dense(32, activation='relu'),                # Dense layer to reduce dimensionality
    tf.keras.layers.Dense(OUTPUT_DIM, activation='softmax')      # Output layer with softmax for class probabilities
])

In [16]:
model_I.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [118]:
# Iterate through the dataset to extract labels
labels = []

for inputs, label in dataset_method_I:
    labels.append(label)

# Convert to a tensor or numpy array
y_train = np.concatenate(labels, axis=0)  # Stack labels into a single array
y_train_flat = y_train.reshape(-1, 6)  # Flattening the labels: (num_samples * 10, 6)
y_train_classes = np.argmax(y_train_flat, axis=-1)  # Get the class labels for each timestep (0 to 5)

# Calculate class weights based on the frequency of each class
class_weights = compute_class_weight('balanced', classes=np.unique(y_train_classes), y=y_train_classes)

# Convert class_weights into a dictionary format for fit() function
class_weight_dict = {i: class_weights[i] for i in range(len(class_weights))}

In [119]:
print(class_weights)

[1.69060938e-01 2.54473304e+01 2.90288066e+01 5.34393939e+02
 2.02701149e+02 2.26089744e+02]


In [120]:
print(class_weight_dict)

{0: 0.1690609376722605, 1: 25.447330447330447, 2: 29.02880658436214, 3: 534.3939393939394, 4: 202.70114942528735, 5: 226.0897435897436}


In [17]:
history = model_I.fit(dataset_method_I, epochs=50, batch_size=BATCH_SIZE)

Epoch 1/50
112/112 ━━━━━━━━━━━━━━━━━━━━ 13s 41ms/step - accuracy: 0.4221 - loss: 0.1510
Epoch 2/50
112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 24ms/step - accuracy: 0.4316 - loss: 0.1276
Epoch 3/50
112/112 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.6244 - loss: 0.1177
Epoch 4/50
112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 26ms/step - accuracy: 0.6426 - loss: 0.1162
Epoch 5/50
112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 25ms/step - accuracy: 0.6179 - loss: 0.1152
Epoch 6/50
112/112 ━━━━━━━━━━━━━━━━━━━━ 2s 22ms/step - accuracy: 0.6953 - loss: 0.1171
Epoch 7/50
112/112 ━━━━━━━━━━━━━━━━━━━━ 2s 21ms/step - accuracy: 0.7062 - loss: 0.1161
Epoch 8/50
112/112 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.6715 - loss: 0.1146
Epoch 9/50
112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - accuracy: 0.7602 - loss: 0.1117
Epoch 10/50
112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 23ms/step - accuracy: 0.7168 - loss: 0.1154
Epoch 11/50
112/112 ━━━━━━━━━━━━━━━━━━━━ 3s 26ms/step - accuracy: 0.7537 - loss: 0.1144
Epoch 12/50
112/112 ━━━━━━━━━━━━━━━━━━━━

In [18]:
model_I.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lambda_1 (Lambda)               │ (None, 20, 515)        │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 20, 128)        │       296,960 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 20, 32)         │         4,128 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 20, 6)          │           198 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 903,860 (3.45 MB)

 Trainable params: 301,286 (1.15 MB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 602,574 (2.30 MB)

In [19]:
# Evaluate the model
loss, acc = model_I.evaluate(MAAP_test_method_I, verbose=2)
print("Untrained model, accuracy: {:5.2f}%".format(acc))

36/36 - 5s - 141ms/step - accuracy: 0.9809 - loss: 0.1275
Untrained model, accuracy:  0.98%


In [20]:
model_I.save(os.path.join(path, 'model_method_I/model.keras'))

In [115]:
for inputs, labels in dataset_method_I.take(1):  # Take a small batch
    preds = model_I.predict(inputs)
    print("Predictions:", preds)
    print("Ground Truth:", labels)

1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step
Predictions: [[[0.18423472 0.18805367 0.15358369 0.15975992 0.14348555 0.17088243]
  [0.18988968 0.13390423 0.15667434 0.17703208 0.17288329 0.16961627]
  [0.15876924 0.12157965 0.1510373  0.21069701 0.19562545 0.16229136]
  ...
  [0.2360522  0.11189648 0.14936432 0.21476454 0.17604093 0.11188145]
  [0.19055042 0.13608056 0.1481003  0.2175018  0.17827131 0.1294956 ]
  [0.1851553  0.13742118 0.17442626 0.21284981 0.16557454 0.1245729 ]]

 [[0.12943289 0.15690541 0.24211912 0.20530048 0.16510516 0.10113697]
  [0.1359072  0.12828828 0.29404885 0.22961743 0.13318458 0.07895364]
  [0.15133195 0.1261013  0.30664647 0.21946089 0.11806839 0.07839099]
  ...
  [0.16341293 0.13049836 0.26789552 0.14440988 0.19457927 0.099204  ]
  [0.16080208 0.12511742 0.27074748 0.20283565 0.16643985 0.07405749]
  [0.2062359  0.11890065 0.2678376  0.18631993 0.14456865 0.07613719]]

 [[0.16589867 0.12919189 0.14554487 0.19906464 0.21806522 0.14223465]
  [0.19285446 0.07644825 

## MODEL II

In [61]:
model_II = tf.keras.Sequential([
    tf.keras.layers.Input(shape=(SEQUENCE_LENGTH, INPUT_DIM)),    # Input shape: (sequence_length, features)
    tf.keras.layers.LSTM(64, return_sequences=True),              # LSTM layer to capture temporal patterns
    tf.keras.layers.Dense(32, activation='relu'),                 # Dense layer to reduce dimensionality
    tf.keras.layers.Dense(OUTPUT_DIM, activation='sigmoid')       # Output layer with sigmoid for continuous values between 0 and 1
])

In [ ]:
def mask_timestep(inputs):
    # Mask timesteps where any feature is 0
    # tf.reduce_any checks if any feature in the timestep is 0
    mask = tf.reduce_any(tf.equal(inputs, 0.0), axis=-1)  # Create mask for timesteps with any 0
    return mask

# Input Layer
inputs = tf.keras.Input(shape=(SEQUENCE_LENGTH, INPUT_DIM))

# Apply the custom masking logic
mask = tf.keras.layers.Lambda(mask_timestep)(inputs)

# Apply the mask to the input sequence (this will zero out timesteps that have missing values)
masked_inputs = tf.keras.layers.Masking(mask_value=0.0)(inputs)

# LSTM layers to process the masked inputs
lstm_output = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64, return_sequences=True))(masked_inputs)

# Dense layers
dense_output = tf.keras.layers.Dense(32, activation='relu')(lstm_output)
output = tf.keras.layers.Dense(OUTPUT_DIM, activation='sigmoid')(dense_output)

# Build and compile the model
model_I = tf.keras.Model(inputs=inputs, outputs=output)

In [62]:
model_II.compile(optimizer='adam', loss='mean_squared_error', metrics=['mae'])

In [63]:
history = model_II.fit(dataset_method_II, epochs=50)

Epoch 1/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 9s 24ms/step - loss: 0.0663 - mae: 0.1861
Epoch 2/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - loss: 0.0117 - mae: 0.0421
Epoch 3/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 4s 18ms/step - loss: 0.0108 - mae: 0.0378
Epoch 4/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - loss: 0.0104 - mae: 0.0362
Epoch 5/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 0.0096 - mae: 0.0343
Epoch 6/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 0.0094 - mae: 0.0339
Epoch 7/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 3s 14ms/step - loss: 0.0089 - mae: 0.0328
Epoch 8/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 0.0085 - mae: 0.0318
Epoch 9/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 0.0083 - mae: 0.0310
Epoch 10/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 0.0079 - mae: 0.0297
Epoch 11/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 4s 17ms/step - loss: 0.0077 - mae: 0.0292
Epoch 12/50
225/225 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - loss: 0.0075 - mae: 0.0284
Epoch 13/50
2

In [64]:
model_II.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm_5 (LSTM)                   │ (None, 10, 64)         │       148,480 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 10, 32)         │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 10, 6)          │           198 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 452,276 (1.73 MB)

 Trainable params: 150,758 (588.90 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 301,518 (1.15 MB)

In [65]:
# Evaluate the model
loss, acc = model_II.evaluate(MAAP_test_method_II, verbose=2)
print("Untrained model, coherence: {:5.2f}%".format(100 * (1-acc)))

72/72 - 3s - 44ms/step - loss: 0.0120 - mae: 0.0367
Untrained model, coherence: 96.33%


In [66]:
model_II.save(os.path.join(path, 'model_method_II/model.keras'))

## Transformer

In [87]:
from tensorflow.keras import layers, Model
from tensorflow.keras.layers import Input, Dense, LayerNormalization, MultiHeadAttention, Dropout

In [102]:
def get_positional_encoding(sequence_length, input_dim):
    """
    Generate a positional encoding matrix for the transformer model.
    This encoding is added to the input data to give the model an understanding of the order of the sequence.
    """
    position = np.arange(sequence_length)[:, np.newaxis]  # Shape: (sequence_length, 1)
    div_term = np.exp(np.arange(0, input_dim, 2) * -(np.log(10000.0) / input_dim))  # Shape: (input_dim // 2,)
    
    pos_enc = np.zeros((sequence_length, input_dim))  # Shape: (sequence_length, input_dim)
    
    # Apply sine to even indices (0, 2, 4, ...)
    pos_enc[:, 0::2] = np.sin(position * div_term)  # Apply sine to even indices (0, 2, 4, ...)
    pos_enc[:, 1::2] = np.cos(position * div_term)
    # Apply cosine to odd indices (1, 3, 5, ...)
    if input_dim % 2 != 0:  # Even input_dim
        pos_enc[:, -1] = np.sin(position * div_term[-1])  # If odd, handle the last dimension separately

    return tf.constant(pos_enc, dtype=tf.float32)



In [103]:
def transformer_encoder(inputs, head_size, num_heads, ff_dim, dropout_rate):
    # Multi-Head Self Attention Layer
    attention_output = tf.keras.layers.MultiHeadAttention(num_heads=num_heads, key_dim=head_size, dropout=dropout_rate)(inputs, inputs)
    
    # Skip connection and normalization
    x = tf.keras.layers.Add()([inputs, attention_output])
    x = tf.keras.layers.LayerNormalization(epsilon=1e-6)(x)
    
    # Feed-forward network
    ffn_output = tf.keras.layers.Dense(ff_dim, activation='relu')(x)
    ffn_output = tf.keras.layers.Dense(inputs.shape[-1])(ffn_output)
    
    # Skip connection and normalization
    x = tf.keras.layers.Add()([x, ffn_output])
    x = tf.keras.layers.LayerNormalization(epsilon=1e-6)(x)
    
    return x

In [104]:
def build_transformer_model(sequence_length, input_dim, output_dim, num_heads=8, ff_dim=128, num_layers=4, dropout_rate=0.1):
    inputs = tf.keras.Input(shape=(sequence_length, input_dim))  # Input shape
    
    # Add positional encoding to inputs
    pos_encoding = get_positional_encoding(sequence_length, input_dim)
    x = tf.keras.layers.Add()([inputs, pos_encoding])  # Adding positional encoding to input
    
    # Pass through multiple Transformer encoder blocks
    for _ in range(num_layers):
        x = transformer_encoder(x, head_size=input_dim, num_heads=num_heads, ff_dim=ff_dim, dropout_rate=dropout_rate)
    
    # Global Average Pooling
    x = tf.keras.layers.GlobalAveragePooling1D()(x)
    
    # Dense layers
    x = tf.keras.layers.Dense(64, activation='relu')(x)
    x = tf.keras.layers.Dropout(0.5)(x)
    output = tf.keras.layers.Dense(output_dim, activation='sigmoid')(x)  # Output layer with 6 emotions
    
    # Build the model
    model = tf.keras.Model(inputs=inputs, outputs=output)
    return model

In [105]:
# Dataset dimensions (example values)
sequence_length = 10  # Length of each sequence (e.g., 10 frames per video)
input_dim = 515  # Number of features per timestep (e.g., face embeddings with 515 features)
output_dim = 6  # Number of classes (emotions)

# Build the model
model = build_transformer_model(sequence_length, input_dim, output_dim)

ValueError: could not broadcast input array from shape (10,258) into shape (10,257)

In [ ]:
# Summary of the model
model.summary()

# Assuming you have `X_train` and `y_train` loaded from your dataset
# Model training
history = model.fit(dataset_method_I,epochs=50, batch_size=32)